---
driver:
  name: vagrant
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  client_rb:
    environment: stage

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      cpus: 4
      memory: 1536
    network:
      - - private_network
        - ip: '192.168.33.10'

suites:
- name: default
  run_list:
    - recipe[nginx]
    - recipe[et_hostname]
    - recipe[et_haproxy]
  attributes:
    et_hostname:
      addl_hosts_entries:
        - 10.4.0.2 stage-hadoop-nn-1b
        - 10.4.0.3 stage-logs-1b
        - 10.4.0.4 stage-api-1.priv.evertrue.com
    nginx:
      port: 8123
    haproxy:
      acls:
        host_stage-api:
          type: hdr_beg(host)
          match: stage-api.evertrue.com
        uri_search:
          type: path_beg
          match: /search
      frontends:
        vpn_fe:
          vpn: true
          ports:
          - '8081'
          redirect_port: '8443'
        main:
          ports:
          - '80'
          - '8080'
          ssl: false
        main_ssl:
          port: '8443'
          ports:
          - '8443'
          ssl: true
      applications:
        searchapi-stage:
          acls:
          - - host_stage-api
            - uri_search
          access_control: true
          allowed:
            host_groups:
            - set_global
            - eips
            - instance_ext_ips
          endpoint: stage-searchapi.evertrue.com
          ssl_enabled: true
          ssl_disable_redirect: true
          ssl_required: true
          backend: searchapi-stage
        just-block:
          acls:
          - - hdr_etapptoken
          - - uri_param_etapptoken
          allowed:
            host_groups:
            - set_global
            - eips
            - instance_ext_ips
          ssl_enabled: true
          access_control: false
      backends:
        searchapi-stage:
          balance_algorithm: roundrobin
          check_req:
            method: OPTIONS
            url: /search/
          port: '8080'
          servers_recipe: et_search_api
        legacyapi-stage:
          balance_algorithm: roundrobin
          check_req:
            always: true
          servers:
          - name: stage-api-1
            fqdn: stage-api-1.priv.evertrue.com
            port: '8080'
