---
driver:
  name: ec2
  require_chef_omnibus: true
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  username: ubuntu
  flavor_id: c3.large
  interface: public

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/encrypted_data_bag_secret
  client_rb:
    environment: dev

platforms:
- name: ubuntu-12.04
  driver_config:
    image_id: ami-36aa4d5e
    tags:
      Name: travis-ci-default-ubuntu-1204
      Env: public

suites:
- name: default
  run_list:
    - recipe[apt::default]
    - recipe[et_nginx::default]
    - recipe[et_hostname]
    - recipe[et_users]
    - recipe[et_haproxy]
    - recipe[et_haproxy::newrelic]
  attributes:
    et_hostname:
      addl_hosts_entries:
        - 10.4.0.2 stage-hadoop-nn-1b
        - 10.4.0.3 stage-logs-1b
        - 10.4.0.4 stage-api-1.priv.evertrue.com
    nginx:
      port: 8123
    haproxy:
      access_control:
        use_eips: false
        use_instance_ips: false
        sets:
        - global
        - local
      acls:
        host-api:
          type: hdr(host)
          match: api.local
        uri_search:
          type: path_beg
          match: /search
        host-block:
          type: hdr(host)
          match: block.local
        one_more_rule:
          type: path_beg
          match: /one_more_rule
        exempt_from_access_control:
          type: hdr(host)
          match: access-control-exempt.local
        uri_host_without_endpoint:
          type: path
          match: /uri_host_without_endpoint
        uri_ssl-redirect-host-with-endpoint:
          type: path
          match: /uri_ssl-redirect-host-with-endpoint
      frontends:
        vpn_fe:
          vpn: true
          ports:
          - '8081'
          redirect_port: '8443'
        main:
          ports:
          - '80'
          - '8080'
          ssl: false
        main_ssl:
          port: '8443'
          ports:
          - '8443'
          ssl: true
      applications:
        host-endpoint-only:
          endpoint: hostendpointonly.local
          ssl_enabled: false
          backend: host-endpoint-only
        host-with-endpoint:
          acls:
          - - host-api
            - uri_search
          - - host-api
            - one_more_rule
          endpoint: host-with-endpoint.local
          ssl_enabled: false
          backend: host-with-endpoint
        host-without-endpoint:
          acls:
          - - host-api
            - uri_search
            - one_more_rule
          ssl_enabled: false
          backend: host-without-endpoint
        ssl-host-with-endpoint:
          acls:
          - - host-api
            - uri_search
          endpoint: ssl-host-with-endpoint.local
          ssl_enabled: true
          ssl_disable_redirect: true
          ssl_required: true
          backend: ssl-host-with-endpoint
        ssl-redirect-host-with-endpoint:
          acls:
          - - host-api
            - uri_search
            - uri_ssl-redirect-host-with-endpoint
          endpoint: ssl-redirect-host-with-endpoint.local
          ssl_enabled: true
          ssl_disable_redirect: false
          ssl_required: true
          backend: ssl-redirect-host-with-endpoint
        ssl-host-without-endpoint:
          acls:
          - - host-api
            - uri_search
            - uri_host_without_endpoint
          access_control: true
          allowed:
            host_groups:
            - set_global
          ssl_enabled: true
          ssl_disable_redirect: true
          ssl_required: true
          backend: ssl-host-without-endpoint
        just-block:
          acls:
          - - uri_search
            - host-block
          allowed:
            host_groups:
            - set_global
          ssl_enabled: true
          access_control: true
      backends:
        host-endpoint-only:
          balance_algorithm: roundrobin
          check_req:
            always: true
            method: OPTIONS
            url: /search/
          port: '8080'
          servers_recipe: et_generic_api::default
        host-with-endpoint:
          balance_algorithm: roundrobin
          check_req:
            always: false
          servers:
          - name: stage-api-1
            fqdn: stage-api-1.local
            port: '8080'
          - name: stage-api-2
            fqdn: stage-api-2.local
            port: '8080'
        host-without-endpoint:
          port: '8080'
          servers_recipe: et_generic_api
        ssl-host-with-endpoint:
          balance_algorithm: roundrobin
          check_req:
            always: true
          servers:
          - name: stage-api-1
            fqdn: stage-api-1.local
            port: '8080'
          - name: stage-api-2
            fqdn: stage-api-2.local
            port: '8080'
        ssl-redirect-host-with-endpoint:
          balance_algorithm: roundrobin
          check_req:
            method: OPTIONS
            url: /search/
          port: '8080'
          servers_recipe: et_generic_api_cluster
        ssl-host-without-endpoint:
          balance_algorithm: roundrobin
          check_req:
            always: true
          servers:
          - name: stage-api-1
            fqdn: stage-api-1.local
            port: '8080'
    newrelic_meetme_plugin:
      license: TESTKEY_PLUGIN_AGENT
      service_notify_action: nothing
      service_actions:
        - enable
