---
driver:
  name: vagrant
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  environments_path: '.chef-zero/environments'
  nodes_path: '.chef-zero/nodes'
  data_bags_path: '.chef-zero/data_bags'

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      cpus: 4
      memory: 1536
    network:
      - [ 'private_network', {ip: '192.168.33.10'}]
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

# platforms:
# - name: ubuntu-12.04
#   driver:
#     username: ubuntu
#     image_id: ami-cf5e2ba6
#     vm:
#       provision:
#         - ['shell', {inline: 'sudo mkdir -p /var/chef && sudo ln -sf /vagrant/.chef-repo/data_bags /var/chef/data_bags'}]

suites:
- name: default
  run_list: [
    'recipe[nginx]',
    'recipe[et_hostname]',
    'recipe[et_haproxy]'
  ]
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  provisioner:
    client_rb:
      environment: 'stage'
  attributes:
    et_hostname:
      addl_hosts_entries:
        - '10.4.0.2 stage-hadoop-nn-1b'
        - '10.4.0.3 stage-logs-1b'
        - '10.4.0.4 stage-api-1.priv.evertrue.com'
    nginx:
      port: 8123
  #     socketproxy:
  #       root: '/usr/share/evertrue'
  #       app_owner: 'nginx'
  #       default_app: 'default'
  #       apps:
  #         default:
  #           prepend_slash: false
  #           context_name: ''
  #           subdir: 'current'
  #           socket:
