name             'et_haproxy'
maintainer       'EverTrue, Inc.'
maintainer_email 'eric.herot@evertrue.com'
license          'All rights reserved'
description      'Installs/Configures et_haproxy'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '3.3.3'

depends 'apt'
depends 'openssl'
depends 'logrotate', '~> 1.7'
depends 'et_fog', '~> 1.1'
depends 'stunnel', '~> 2.1'
depends 'certificate'
depends 'newrelic-ng', '~> 0.5'
depends 'sudo', '~> 2.7'
depends 'et_users', '~> 1.4'
depends 'et_security', '~> 1.2'
depends 'zookeeper', '~> 2.4'
depends 's3_file'
depends 'java', '~> 1.28'
